services:
  # MySQL Database
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - ./data/init.sql:/data/init.sql
    command: --init-file /data/init.sql

  # NestJS Application
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    restart: on-failure
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: admin
      DB_NAME: blog
      JWT_SECRET: 123456
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules 
      

volumes:
  mysql-data:
