version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:5.7
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  # NestJS Application
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 1234
      DB_USERNAME: nolimit-task
      DB_PASSWORD: nolimit-task1
      DB_NAME: blog
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules 
      

volumes:
  mysql-data:
